### ISSUE TITLE
Issues in Android Tamer Live CD #1

### ISSUE THREAD

**Issue by 0xbadshah** [AndroidTamer/Tools_Repository#61] opened 2016-05-30 03:46 UTC
## Issues in Android Tamer Live CD
- Development
  - hierarchyviewer not working from menu. Change the command in the menu item.

There is an additional error message for some programs:

  `_plugin__start_agent:7: no such file or directory: /home/android/.ssh/environment-tamer
chmod: cannot access ‘/home/android/.ssh/environment-tamer’: No such file or directory
_plugin__start_agent:.:9: no such file or directory: /home/android/.ssh/environment-tamer
starting ssh-agent...`

The programs which show the error are:
- Traceview (Development)
- Volatility (Forensics)
- pidcat (Manual Analysis)
- baksmali (RE)
- dex2jar (RE)
- drozer start (RE)
- Enjarify (RE)
- JAD (RE)
- JD GUI (RE)
- Smali (RE)
### Additional Improvements required

 It would be better if the Live CD automatically detects the screen size and adjusts to it when the VM runs in full screen.

**Comment by anantshri** [comment] 2016-05-30 03:54
hierarchyviewer should be easy to correct its already in pull requests we just need to create package and push it out.

Error message is something i need to check.

auto resize is also something i will have to check.

**Comment by anantshri** [comment] 2016-05-30 12:59
Tracked down the cause of error : https://github.com/robbyrussell/oh-my-zsh/issues/5128 temp fix would be to ensure .ssh is kept but hopefully ohmyzsh fix would be a permanent fix.

BTW autoresize is working on my virtualbox. Can you confirm what version of Virtualbox are you using.

**Comment by 0xbadshah** [comment] 2016-05-30 16:15
My virtualbox version: 5.0.16 r105871

**Comment by 0xbadshah** [comment] 2016-05-30 16:18
I also feel changing `Log Off User` and `ShutDown` to the bottom of the menu is a better idea.

**Comment by anantshri** [comment] 2016-05-30 16:49
Sorting of menu is not under my control at this point. I am trying to see how i can do that but that might take some time. Can you try upgrading your VBox to 5.0.20 i have 5.0.20 guest additions installed on that iso.

**Comment by anantshri** [comment] 2017-03-08 14:42
closing these bugs as i will try recreating the iso using differnet software this time.  all to be tracked https://github.com/AndroidTamer/Tools_Repository/issues/60

**Closed as completed by anantshri** 2017-03-08 14:42 UTC
Labels: bug, iso-bugs, Tamer-5
